# Generated by Django 3.2.16 on 2023-01-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_alter_subscription_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
    ]
