# Generated by Django 3.2.16 on 2023-01-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_auto_20230109_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcomment',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
