# Generated by Django 3.2.16 on 2023-01-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
